apiVersion: v1
kind: Service
metadata:
  name: frontend-nxt-service
  labels:
    app: frontend-nxt
spec:
  selector:
    app: frontend-nxt
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
